services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    restart: always
    container_name: mlflow
    ports:
      - "5001:5001"
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
      - ./mlflow_data:/mlflow/data  # Новая папка для SQLite
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/data/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5001
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
    driver: local
  mlflow_data:  # Новый volume для SQLite
    driver: local