version: '3'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6334:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow_data:/mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000